{{- range $i, $client := $.Values.clients -}}
{{- range $j, $env := $.Values.envs -}}
{{- /* Could put common config layers in here as well */ -}}
{{- $client_env_config := $.Files.Get (printf "client/%s/%s.yaml" $client $env) | fromYaml -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: train-{{$client}}-{{$env}}
  namespace: argocd

spec:

  destination:
    namespace: {{$env}}
    server: https://kubernetes.default.svc

  project: default # release-train-project

  source:
    repoURL: "https://github.com/emarcotte/deployment-config"
    path: 'apps/deployment-app-1'
    targetRevision: release
    helm:
      parameters:
        - name: image.tag
          value: {{ required (printf "Ensure that client/%s/%s.yaml set cool_app.version" $client $env) $client_env_config.cool_app.version }}

  syncPolicy:
    automated: {}
{{ end }}{{ end }}

