{{- range $i, $client := $.Values.clients -}}
{{- range $j, $env := $.Values.envs -}}
{{- /* Could put common config layers in here as well */ -}}
{{- $client_env_config := $.Files.Get (printf "client/%s/%s.yaml" $client $env) | fromYaml -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: train-{{$env}}
  namespace: {{ required (printf "Ensure that client/%s/%s.yaml set ns" $client $env) $client_env_config.ns }}
spec:

  destination:
    namespace: {{ required (printf "Ensure that client/%s/%s.yaml set ns" $client $env) $client_env_config.ns }}
    server: https://kubernetes.default.svc

  project: release-train-project

  source:
    repoURL: "https://github.com/emarcotte/deployment-config"
    path: ''
    targetRevision: release
    helm:
      parameters:
        - name: image.tag
          value: {{ required (printf "Ensure that client/%s/%s.yaml set cool_app.version" $client $env) $client_env_config.cool_app.version }}

  syncPolicy:
    automated: {}
{{ end }}{{ end }}

