{{- $values := .Values -}}
{{- range $i, $client := $values.clients -}}
{{- range $j, $env := $values.envs -}}
{{- /* Could put common config layers in here as well */ -}}
{{- $client_env_config := $.Files.Get (printf "client/%s/%s.yaml" $client $env) | fromYaml -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: train-{{$env}}
  namespace: {{ $client_env_config.ns }}
  client_config: {{ include "toYaml" $client_env_config | indent 2 }}
spec:

  destination:
    namespace: {{ $env }}
    server: https://kubernetes.default.svc

  project: release-train-project

  source:
    repoURL: "https://github.com/emarcotte/deployment-config"
    targetRevision: {{ $client_env_config.cool_app.version }}
    helm:
      parameters:
        - name: image.tag
          value: {{ $client_env_config.cool_app.version }}

  syncPolicy:
    automated: {}

{{- end }}
{{- end }}

