---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: train-dev
  namespace: dev
spec:

  destination:
    namespace: dev
    server: https://kubernetes.default.svc

  project: release-train-project

  source:
    repoURL: "https://github.com/emarcotte/deployment-config"
    targetRevision: 1.0.7
    helm:
      parameters:
        - name: image.tag
          value: 1.0.7

  syncPolicy:
    automated: {}
